version: '3.8'
services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
      - MINIO_REGION=us-east-1
      # AMQP Configuration with Identifier "PRIMARY"
      - MINIO_NOTIFY_AMQP_ENABLE_PRIMARY=on
      - MINIO_NOTIFY_AMQP_URL_PRIMARY=amqp://guest:guest@rabbitmq:5672
      - MINIO_NOTIFY_AMQP_EXCHANGE_PRIMARY=minio_exchange
      - MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_PRIMARY=direct
      - MINIO_NOTIFY_AMQP_ROUTING_KEY_PRIMARY=minio_key
      - MINIO_NOTIFY_AMQP_MANDATORY_PRIMARY=false
      - MINIO_NOTIFY_AMQP_DURABLE_PRIMARY=true
      - MINIO_NOTIFY_AMQP_NO_WAIT_PRIMARY=false
      - MINIO_NOTIFY_AMQP_INTERNAL_PRIMARY=false
      - MINIO_NOTIFY_AMQP_AUTO_DELETED_PRIMARY=false
      - MINIO_NOTIFY_AMQP_DELIVERY_MODE_PRIMARY=2
      - MINIO_NOTIFY_AMQP_QUEUE_DIR_PRIMARY=/data/.queue
      - MINIO_NOTIFY_AMQP_QUEUE_LIMIT_PRIMARY=100000
      - MINIO_NOTIFY_AMQP_COMMENT_PRIMARY=Primary RabbitMQ integration
    ports:
      - "9000:9000" # MinIO API
      - "9011:9001" # MinIO Web UI
    volumes:
      - minio-data:/data
      - ./scripts:/scripts  # Mount the `scripts` directory where `init.sh` is located
    depends_on:
      - rabbitmq
    entrypoint: ["/scripts/init.sh"]

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672" # RabbitMQ AMQP port
      - "15672:15672" # RabbitMQ Management UI

volumes:
  minio-data:
